export const ROLES = {
    SUPER_ADMIN: 'SUPER_ADMIN',
    HR_MANAGER: 'HR_MANAGER',
    PROJECT_MANAGER: 'PROJECT_MANAGER',
    TEAM_LEAD: 'TEAM_LEAD',
    FINANCE_MANAGER: 'FINANCE_MANAGER',
    EMPLOYEE: 'EMPLOYEE',
    TRAINEE: 'TRAINEE',
};

export const PERMISSIONS = {
    // Module Access
    ACCESS_DASHBOARD: 'ACCESS_DASHBOARD',
    ACCESS_ATTENDANCE: 'ACCESS_ATTENDANCE',
    ACCESS_LEAVES: 'ACCESS_LEAVES',
    ACCESS_PAYROLL: 'ACCESS_PAYROLL',
    ACCESS_PERFORMANCE: 'ACCESS_PERFORMANCE',
    ACCESS_PROJECTS: 'ACCESS_PROJECTS',
    ACCESS_RECRUITMENT: 'ACCESS_RECRUITMENT',
    ACCESS_SETTINGS: 'ACCESS_SETTINGS',
    ACCESS_USER_MGMT: 'ACCESS_USER_MGMT',

    // Feature specific
    VIEW_SALARY: 'VIEW_SALARY',
    MANAGE_USERS: 'MANAGE_USERS',
    APPROVE_LEAVES: 'APPROVE_LEAVES',
    MANAGE_PROJECTS: 'MANAGE_PROJECTS',
};

// Simple matrix: Role -> [Permissions]
// In a real app, this might be more granular or DB driven, but for now we hardcode the policy.
export const ROLE_PERMISSIONS = {
    [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
    [ROLES.HR_MANAGER]: [
        PERMISSIONS.ACCESS_DASHBOARD,
        PERMISSIONS.ACCESS_ATTENDANCE,
        PERMISSIONS.ACCESS_LEAVES,
        PERMISSIONS.ACCESS_RECRUITMENT,
        PERMISSIONS.ACCESS_PERFORMANCE,
        PERMISSIONS.ACCESS_USER_MGMT, // Limited
        PERMISSIONS.APPROVE_LEAVES,
    ],
    [ROLES.PROJECT_MANAGER]: [
        PERMISSIONS.ACCESS_DASHBOARD,
        PERMISSIONS.ACCESS_PROJECTS,
        PERMISSIONS.MANAGE_PROJECTS,
        PERMISSIONS.ACCESS_PERFORMANCE, // Review team performance in context of projects
    ],
    [ROLES.TEAM_LEAD]: [
        PERMISSIONS.ACCESS_DASHBOARD,
        PERMISSIONS.ACCESS_ATTENDANCE,
        PERMISSIONS.ACCESS_LEAVES,
        PERMISSIONS.ACCESS_PROJECTS, // View only typically, or manage tasks
        PERMISSIONS.ACCESS_PERFORMANCE,
        PERMISSIONS.APPROVE_LEAVES,
    ],
    [ROLES.FINANCE_MANAGER]: [
        PERMISSIONS.ACCESS_DASHBOARD,
        PERMISSIONS.ACCESS_PAYROLL,
        PERMISSIONS.VIEW_SALARY,
    ],
    [ROLES.EMPLOYEE]: [
        PERMISSIONS.ACCESS_DASHBOARD,
        PERMISSIONS.ACCESS_ATTENDANCE,
        PERMISSIONS.ACCESS_LEAVES,
        PERMISSIONS.ACCESS_PROJECTS,
        PERMISSIONS.ACCESS_PERFORMANCE, // Self
    ],
    [ROLES.TRAINEE]: [
        PERMISSIONS.ACCESS_DASHBOARD,
        PERMISSIONS.ACCESS_ATTENDANCE,
        PERMISSIONS.ACCESS_LEAVES, // View
    ],
};
